//! Measures what this app stores on disk, and evicts down to a budget.
//!
//! # What "total app disk usage" means here
//!
//! Everything under the app-data directory, broken down by component. The
//! breakdown is derived by walking the real directories rather than summing
//! what the database believes: a partial download, an orphaned model folder or
//! a WAL file that grew are all real bytes on the user's disk, and a figure
//! that omitted them would be wrong in exactly the situation where the user
//! went looking for it.
//!
//! # Eviction is tiered, not a flat LRU
//!
//! "Delete the oldest thing" cannot be applied uniformly, because some of
//! these bytes are load-bearing:
//!
//! - the inference **engine** is placed by the NSIS installer and there is no
//!   runtime self-heal (`EngineManager::initialize` returns false and model
//!   switching then fails) - deleting it makes the app unusable;
//! - **memory.db** holds every conversation and document record;
//! - the **active model** is in use by the running llama-server;
//! - the **Local Storage vault** is user content, and this repository is not
//!   under version control - a deleted document is gone.
//!
//! So eviction walks tiers in order, stopping as soon as usage is under
//! budget, and stops entirely rather than touching anything protected:
//!
//! 1. **KV cache blobs** - pure derived cache, regenerated by re-prefilling.
//! 1b. **Rendered draft page images** - same standing: regenerated by asking
//!    pdfium for the page again.
//! 2. **Stale downloads** - interrupted partial downloads, resumable.
//! 3. **Non-active installed models**, least-recently-activated first -
//!    large, and re-downloadable from their original source.
//! 4. **Superseded draft versions**, oldest first - the only tier that touches
//!    something the user authored, which is why it is last. The CURRENT version
//!    of every draft and version 1 (the file exactly as it was opened) are
//!    never evicted, so the worst outcome is a shorter history, never a lost
//!    document.
//!
//! If tiers 1-4 cannot free enough, the pass reports the shortfall instead of
//! escalating. A budget that cannot be met is a fact for the user to act on,
//! not a licence to delete their documents.

use serde::Serialize;
use std::path::{Path, PathBuf};
use tracing::{info, warn};

/// Where a disk-limit value came from, so the UI can say so plainly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum LimitSource {
    /// The user chose it in Settings (`app_settings` table).
    UserSetting,
    /// The shipped default from `.env` (`APP_DISK_LIMIT_MB`).
    Environment,
}

/// The disk budget actually in force, and where it came from.
#[derive(Debug, Clone, Copy, Serialize)]
pub struct EffectiveLimit {
    pub limit_mb: u64,
    pub source: LimitSource,
}

impl EffectiveLimit {
    /// A limit of 0 means unlimited - eviction never runs.
    pub fn is_unlimited(&self) -> bool {
        self.limit_mb == 0
    }

    pub fn limit_bytes(&self) -> u64 {
        self.limit_mb.saturating_mul(1024 * 1024)
    }
}

/// Resolve the disk budget: user setting first, then `.env`.
///
/// There is no third fallback here because `Config::app_disk_limit_mb` has
/// already applied `DEFAULT_APP_DISK_LIMIT_MB` for a missing or unparseable
/// env var, so the config value is always a usable number by the time it
/// reaches this function.
pub fn effective_disk_limit_mb(
    database: &crate::memory_db::MemoryDatabase,
    config: &crate::config::Config,
) -> EffectiveLimit {
    match database
        .settings
        .get_u64(crate::memory_db::settings_store::DISK_LIMIT_MB_KEY)
    {
        Some(user_value) => EffectiveLimit {
            limit_mb: user_value,
            source: LimitSource::UserSetting,
        },
        None => EffectiveLimit {
            limit_mb: config.app_disk_limit_mb,
            source: LimitSource::Environment,
        },
    }
}

/// Per-component disk usage, in bytes.
#[derive(Debug, Clone, Default, Serialize)]
pub struct DiskUsage {
    pub models_bytes: u64,
    pub engines_bytes: u64,
    pub database_bytes: u64,
    pub vault_bytes: u64,
    pub downloads_bytes: u64,
    pub kv_cache_bytes: u64,
    /// Drafts: the document workspace's byte copies and version history. User-
    /// AUTHORED work, so the current version of every draft is protected like
    /// the Vault; only superseded versions are evictable (see `run_eviction`).
    pub drafts_bytes: u64,
    /// Anything else under the app-data directory (logs, the WebView2 profile,
    /// the executable itself). Counted because the setting promises TOTAL app
    /// disk usage, and reported separately because none of it is evictable.
    pub other_bytes: u64,
    pub total_bytes: u64,
}

/// Names of the immediate app-data subdirectories that are accounted for
/// individually. Anything not in this list lands in `other_bytes`.
const MODELS_DIR: &str = "models";
const ENGINES_DIR: &str = "engines";
const DATA_DIR: &str = "data";
const FILES_DIR: &str = "files";
const DOWNLOADS_DIR: &str = "downloads";
/// Directory for llama-server slot KV blobs. Named here (rather than only
/// where it is created) so usage accounting is correct from the first release
/// that writes one, without a second definition to keep in sync.
pub const KV_CACHE_DIR: &str = "kv_cache";
/// Directory holding draft byte copies and their version history.
pub const DRAFTS_DIR: &str = "drafts";
/// Per-draft subdirectory of rendered page images. Pure derived state: every
/// file in it can be regenerated by asking pdfium for the page again, which is
/// why it is evicted in the same tier as the KV cache rather than being
/// treated as the user's work.
pub const PAGE_CACHE_DIR: &str = ".cache";

/// Total size of a directory tree, following the same walk `ModelStorage`
/// uses. Missing directories are 0, not an error: a fresh install has no
/// `downloads/` until the first download starts.
pub fn directory_size(path: &Path) -> u64 {
    if !path.exists() {
        return 0;
    }
    let mut total = 0u64;
    for entry in walkdir::WalkDir::new(path).into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() {
            if let Ok(meta) = entry.metadata() {
                total = total.saturating_add(meta.len());
            }
        }
    }
    total
}

/// Measure every component under `app_data_dir`.
///
/// The walk is filesystem-truth. In particular `database_bytes` covers the
/// whole `data/` directory rather than just `memory.db`, because SQLite in WAL
/// mode also keeps `-wal` and `-shm` alongside it and the `-wal` file can be
/// substantial.
pub fn measure(app_data_dir: &Path) -> DiskUsage {
    let models_bytes = directory_size(&app_data_dir.join(MODELS_DIR));
    let engines_bytes = directory_size(&app_data_dir.join(ENGINES_DIR));
    let database_bytes = directory_size(&app_data_dir.join(DATA_DIR));
    let vault_bytes = directory_size(&app_data_dir.join(FILES_DIR));
    let downloads_bytes = directory_size(&app_data_dir.join(DOWNLOADS_DIR));
    let kv_cache_bytes = directory_size(&app_data_dir.join(KV_CACHE_DIR));
    let drafts_bytes = directory_size(&app_data_dir.join(DRAFTS_DIR));

    let total_bytes = directory_size(app_data_dir);
    let accounted = models_bytes
        .saturating_add(engines_bytes)
        .saturating_add(database_bytes)
        .saturating_add(vault_bytes)
        .saturating_add(downloads_bytes)
        .saturating_add(kv_cache_bytes)
        .saturating_add(drafts_bytes);

    DiskUsage {
        models_bytes,
        engines_bytes,
        database_bytes,
        vault_bytes,
        downloads_bytes,
        kv_cache_bytes,
        drafts_bytes,
        other_bytes: total_bytes.saturating_sub(accounted),
        total_bytes,
    }
}

/// One thing eviction removed.
#[derive(Debug, Clone, Serialize)]
pub struct EvictedItem {
    /// "kv_cache" | "page_cache" | "download" | "model" | "draft_version"
    pub kind: String,
    /// Model id, file name, or "draft {id} v{n}".
    pub id: String,
    pub freed_bytes: u64,
}

/// Outcome of one eviction pass. Always describes what happened, including
/// the case where nothing needed doing.
#[derive(Debug, Clone, Serialize)]
pub struct EvictionOutcome {
    pub ran: bool,
    pub usage_before_bytes: u64,
    pub usage_after_bytes: u64,
    pub limit_bytes: u64,
    pub freed_bytes: u64,
    pub evicted: Vec<EvictedItem>,
    /// Bytes still over budget after every evictable tier was exhausted.
    /// Non-zero means the protected set alone exceeds the limit.
    pub shortfall_bytes: u64,
    /// Plain-language account of what the pass did and why.
    pub reason: String,
}

/// What eviction is allowed to touch, supplied by the caller.
///
/// `active_model_id` is passed in rather than looked up here so this module
/// stays free of runtime state and can be tested with a bare directory.
pub struct EvictionContext<'a> {
    pub app_data_dir: PathBuf,
    /// Model currently loaded in llama-server, if any. Never evicted.
    pub active_model_id: Option<String>,
    /// Installed model ids paired with their on-disk directory.
    pub installed_models: Vec<(String, PathBuf)>,
    pub database: &'a crate::memory_db::MemoryDatabase,
}

/// Bring usage under `limit` by evicting in tier order.
///
/// Returns without deleting anything when the limit is unlimited or already
/// satisfied - the common case, and it must stay cheap.
pub fn enforce_limit(ctx: &EvictionContext, limit: EffectiveLimit) -> EvictionOutcome {
    let usage_before = measure(&ctx.app_data_dir).total_bytes;
    let limit_bytes = limit.limit_bytes();

    if limit.is_unlimited() {
        return EvictionOutcome {
            ran: false,
            usage_before_bytes: usage_before,
            usage_after_bytes: usage_before,
            limit_bytes: 0,
            freed_bytes: 0,
            evicted: Vec::new(),
            shortfall_bytes: 0,
            reason: "no eviction: the disk limit is set to unlimited".to_string(),
        };
    }

    if usage_before <= limit_bytes {
        return EvictionOutcome {
            ran: false,
            usage_before_bytes: usage_before,
            usage_after_bytes: usage_before,
            limit_bytes,
            freed_bytes: 0,
            evicted: Vec::new(),
            shortfall_bytes: 0,
            reason: format!(
                "no eviction needed: {} of {} used",
                format_bytes(usage_before),
                format_bytes(limit_bytes)
            ),
        };
    }

    let mut to_free = usage_before.saturating_sub(limit_bytes);
    let mut evicted: Vec<EvictedItem> = Vec::new();
    let mut freed = 0u64;

    info!(
        "Disk budget exceeded: {} used against a {} limit - {} must be freed",
        format_bytes(usage_before),
        format_bytes(limit_bytes),
        format_bytes(to_free)
    );

    // ── Tier 1: KV cache blobs ────────────────────────────────────────────
    // Pure derived state. Deleting one costs a prompt re-prefill, nothing else.
    let kv_dir = ctx.app_data_dir.join(KV_CACHE_DIR);
    if to_free > 0 && kv_dir.exists() {
        for (path, size) in files_oldest_first(&kv_dir) {
            if to_free == 0 {
                break;
            }
            match std::fs::remove_file(&path) {
                Ok(()) => {
                    freed = freed.saturating_add(size);
                    to_free = to_free.saturating_sub(size);
                    evicted.push(EvictedItem {
                        kind: "kv_cache".to_string(),
                        id: file_label(&path),
                        freed_bytes: size,
                    });
                }
                Err(e) => warn!("Could not evict KV cache blob {}: {}", path.display(), e),
            }
        }
    }

    // ── Tier 1b: rendered draft pages ─────────────────────────────────────
    // Same standing as the KV cache: a cached page image is regenerated by
    // asking pdfium for it again. Costs a re-render, nothing else, so it goes
    // long before anything the user authored.
    if to_free > 0 {
        let drafts_dir = ctx.app_data_dir.join(DRAFTS_DIR);
        if drafts_dir.exists() {
            let caches: Vec<PathBuf> = walkdir::WalkDir::new(&drafts_dir)
                .min_depth(2)
                .max_depth(2)
                .into_iter()
                .filter_map(|e| e.ok())
                .filter(|e| e.file_type().is_dir() && e.file_name() == PAGE_CACHE_DIR)
                .map(|e| e.path().to_path_buf())
                .collect();

            for cache in caches {
                if to_free == 0 {
                    break;
                }
                for (path, size) in files_oldest_first(&cache) {
                    if to_free == 0 {
                        break;
                    }
                    match std::fs::remove_file(&path) {
                        Ok(()) => {
                            freed = freed.saturating_add(size);
                            to_free = to_free.saturating_sub(size);
                            evicted.push(EvictedItem {
                                kind: "page_cache".to_string(),
                                id: file_label(&path),
                                freed_bytes: size,
                            });
                        }
                        Err(e) => warn!("Could not evict rendered page {}: {}", path.display(), e),
                    }
                }
            }
        }
    }

    // ── Tier 2: interrupted downloads ─────────────────────────────────────
    // A partial download is resumable; the bytes are not user content.
    let downloads_dir = ctx.app_data_dir.join(DOWNLOADS_DIR);
    if to_free > 0 && downloads_dir.exists() {
        for (path, size) in files_oldest_first(&downloads_dir) {
            if to_free == 0 {
                break;
            }
            match std::fs::remove_file(&path) {
                Ok(()) => {
                    freed = freed.saturating_add(size);
                    to_free = to_free.saturating_sub(size);
                    evicted.push(EvictedItem {
                        kind: "download".to_string(),
                        id: file_label(&path),
                        freed_bytes: size,
                    });
                }
                Err(e) => warn!("Could not evict partial download {}: {}", path.display(), e),
            }
        }
    }

    // ── Tier 3: non-active models, least recently activated first ─────────
    if to_free > 0 {
        let mut candidates: Vec<(String, PathBuf, u64, Option<chrono::DateTime<chrono::Utc>>)> =
            ctx.installed_models
                .iter()
                .filter(|(id, _)| Some(id.as_str()) != ctx.active_model_id.as_deref())
                .map(|(id, dir)| {
                    let size = directory_size(dir);
                    let last_used = ctx.database.settings.model_last_used(id);
                    (id.clone(), dir.clone(), size, last_used)
                })
                .collect();

        // Never-activated models sort first: a model the user downloaded but
        // never ran is the weakest claim on the disk. Among models that HAVE
        // been activated, oldest activation first.
        candidates.sort_by(|a, b| match (a.3, b.3) {
            (None, None) => a.0.cmp(&b.0),
            (None, Some(_)) => std::cmp::Ordering::Less,
            (Some(_), None) => std::cmp::Ordering::Greater,
            (Some(x), Some(y)) => x.cmp(&y),
        });

        for (model_id, dir, size, _) in candidates {
            if to_free == 0 {
                break;
            }
            match std::fs::remove_dir_all(&dir) {
                Ok(()) => {
                    freed = freed.saturating_add(size);
                    to_free = to_free.saturating_sub(size);
                    if let Err(e) = ctx.database.settings.forget_model(&model_id) {
                        warn!("Evicted model {} but could not clear its recency record: {}", model_id, e);
                    }
                    info!(
                        "Evicted model '{}' ({}) to stay within the disk budget - it can be \
                         downloaded again from the Models page",
                        model_id,
                        format_bytes(size)
                    );
                    evicted.push(EvictedItem {
                        kind: "model".to_string(),
                        id: model_id,
                        freed_bytes: size,
                    });
                }
                Err(e) => warn!("Could not evict model {}: {}", model_id, e),
            }
        }
    }

    // ── Tier 4: superseded draft versions ─────────────────────────────────
    //
    // Last, and deliberately so: this is the only tier that removes something
    // the user made rather than something the app can regenerate or re-fetch.
    //
    // What is NEVER touched here: the current version of any draft, and
    // version 1 — the file exactly as it was opened. So "the original is
    // recoverable forever" survives disk pressure, and the worst outcome is a
    // shorter history, not a lost document. Oldest first, so the most recent
    // intermediate states are the last to go.
    if to_free > 0 {
        match ctx.database.drafts.evictable_versions() {
            Ok(versions) => {
                for version in versions {
                    if to_free == 0 {
                        break;
                    }
                    let path = ctx.app_data_dir.join(&version.storage_path);
                    let size = std::fs::metadata(&path).map(|m| m.len()).unwrap_or(0);

                    // The row goes even if the file was already missing, so a
                    // history entry never points at bytes that are not there.
                    if path.exists() {
                        if let Err(e) = std::fs::remove_file(&path) {
                            warn!("Could not evict draft version {}: {}", path.display(), e);
                            continue;
                        }
                    }
                    if let Err(e) = ctx.database.drafts.delete_version(version.id) {
                        warn!(
                            "Removed {} but could not clear its history row: {}",
                            path.display(),
                            e
                        );
                        continue;
                    }

                    freed = freed.saturating_add(size);
                    to_free = to_free.saturating_sub(size);
                    info!(
                        "Evicted draft {} version {} ({}) to stay within the disk budget - \
                         the current version and the original are untouched",
                        version.draft_id,
                        version.version_no,
                        format_bytes(size)
                    );
                    evicted.push(EvictedItem {
                        kind: "draft_version".to_string(),
                        id: format!("draft {} v{}", version.draft_id, version.version_no),
                        freed_bytes: size,
                    });
                }
            }
            Err(e) => warn!("Could not list evictable draft versions: {}", e),
        }
    }

    let usage_after = measure(&ctx.app_data_dir).total_bytes;
    let shortfall = usage_after.saturating_sub(limit_bytes);

    let reason = if shortfall == 0 {
        format!(
            "freed {} across {} item(s); now {} of {} used",
            format_bytes(freed),
            evicted.len(),
            format_bytes(usage_after),
            format_bytes(limit_bytes)
        )
    } else {
        // Stated, not silently tolerated: the remaining bytes are the engine,
        // the database, the active model and the user's own documents, none of
        // which this pass will delete.
        warn!(
            "Disk budget still exceeded by {} after evicting everything evictable. \
             The remainder is the inference engine, the database, the active model, \
             your Vault documents and your drafts - none of which are removed \
             automatically.",
            format_bytes(shortfall)
        );
        // "Vault" is the product name for the document library, shown in the
        // sidebar and Settings. This string is rendered VERBATIM in the
        // Settings UI (SettingsPanel reads eviction.reason), so it has to use
        // the user-facing name, not the internal one.
        format!(
            "freed {} across {} item(s), but {} is still over the {} limit. The remaining \
             usage is the inference engine, the database, the active model, your Vault \
             documents and your drafts, which are never deleted automatically. Raise the \
             limit, or remove documents or models yourself.",
            format_bytes(freed),
            evicted.len(),
            format_bytes(shortfall),
            format_bytes(limit_bytes)
        )
    };

    EvictionOutcome {
        ran: true,
        usage_before_bytes: usage_before,
        usage_after_bytes: usage_after,
        limit_bytes,
        freed_bytes: freed,
        evicted,
        shortfall_bytes: shortfall,
        reason,
    }
}

/// Files directly inside `dir`, oldest modification time first.
///
/// Falls back to path order when a modification time is unavailable, so the
/// order is always deterministic rather than filesystem-dependent.
fn files_oldest_first(dir: &Path) -> Vec<(PathBuf, u64)> {
    let mut files: Vec<(PathBuf, u64, Option<std::time::SystemTime>)> = Vec::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) => {
            warn!("Could not read {}: {}", dir.display(), e);
            return Vec::new();
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let meta = match entry.metadata() {
            Ok(m) => m,
            Err(_) => continue,
        };
        files.push((path, meta.len(), meta.modified().ok()));
    }
    files.sort_by(|a, b| match (a.2, b.2) {
        (Some(x), Some(y)) => x.cmp(&y),
        (None, Some(_)) => std::cmp::Ordering::Less,
        (Some(_), None) => std::cmp::Ordering::Greater,
        (None, None) => a.0.cmp(&b.0),
    });
    files.into_iter().map(|(p, s, _)| (p, s)).collect()
}

fn file_label(path: &Path) -> String {
    path.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| path.to_string_lossy().to_string())
}

/// Human-readable byte count, matching the style used elsewhere in the API.
pub fn format_bytes(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KB", "MB", "GB", "TB"];
    if bytes == 0 {
        return "0 B".to_string();
    }
    let i = ((bytes as f64).log(1024.0).floor() as usize).min(UNITS.len() - 1);
    let value = bytes as f64 / 1024_f64.powi(i as i32);
    format!("{:.1} {}", value, UNITS[i])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory_db::MemoryDatabase;

    fn write(path: &Path, bytes: usize) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, vec![b'x'; bytes]).unwrap();
    }

    fn temp_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir()
            .join("oca_storage_governor_tests")
            .join(format!("{}_{}", name, std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn ctx<'a>(root: &Path, db: &'a MemoryDatabase) -> EvictionContext<'a> {
        EvictionContext {
            app_data_dir: root.to_path_buf(),
            active_model_id: None,
            installed_models: Vec::new(),
            database: db,
        }
    }

    /// Drafts are measured as their own component, not lumped into "other".
    #[test]
    fn draft_bytes_are_measured_as_drafts() {
        let root = temp_dir("drafts_measured");
        write(&root.join("drafts/1/v1.docx"), 900);
        write(&root.join("drafts/1/v2.docx"), 100);

        let usage = measure(&root);
        assert_eq!(usage.drafts_bytes, 1000);
        assert_eq!(usage.other_bytes, 0, "drafts must not fall into 'other'");
        assert_eq!(usage.total_bytes, 1000);
    }

    /// The eviction contract for drafts, in one test: superseded versions can
    /// go, but the current version and the pristine original never do.
    #[test]
    fn eviction_removes_superseded_draft_versions_but_never_the_original_or_the_current() {
        const MB: usize = 1024 * 1024;
        let root = temp_dir("drafts_evicted");
        let db = MemoryDatabase::new_in_memory().unwrap();

        let draft = db
            .drafts
            .create_draft(
                crate::memory_db::NewDraft {
                    title: "Engagement Letter",
                    format: "docx",
                    origin_kind: "upload",
                    source_document_id: None,
                    source_local_file_id: None,
                },
                "drafts/1/v1.docx",
                MB as i64,
            )
            .unwrap();
        write(&root.join("drafts/1/v1.docx"), MB);

        for version in 2..=4 {
            let path = format!("drafts/{}/v{}.docx", draft.id, version);
            db.drafts.add_version(draft.id, &path, MB as i64, None, None).unwrap();
            write(&root.join(&path), MB);
        }
        assert_eq!(measure(&root).total_bytes as usize, 4 * MB);

        // A 2 MB limit against 4 MB of drafts: exactly the two evictable
        // versions have to go, and nothing else may.
        let limit = EffectiveLimit {
            limit_mb: 2,
            source: LimitSource::UserSetting,
        };
        let outcome = enforce_limit(&ctx(&root, &db), limit);

        let kinds: Vec<&str> = outcome.evicted.iter().map(|e| e.kind.as_str()).collect();
        assert_eq!(kinds, vec!["draft_version", "draft_version"], "{:?}", outcome);

        assert!(root.join("drafts/1/v1.docx").exists(), "the original must survive");
        assert!(root.join("drafts/1/v4.docx").exists(), "the current version must survive");
        assert!(!root.join("drafts/1/v2.docx").exists(), "v2 is superseded");
        assert!(!root.join("drafts/1/v3.docx").exists(), "v3 is superseded");

        // The history must not point at bytes that are gone.
        let remaining: Vec<i64> = db
            .drafts
            .list_versions(draft.id)
            .unwrap()
            .iter()
            .map(|v| v.version_no)
            .collect();
        assert_eq!(remaining, vec![4, 1]);
    }

    #[test]
    fn measure_attributes_bytes_to_the_right_component() {
        let root = temp_dir("measure");
        write(&root.join("models/m1/model.gguf"), 4000);
        write(&root.join("engines/e1/llama-server.exe"), 2000);
        write(&root.join("data/memory.db"), 1000);
        write(&root.join("files/contract.pdf"), 500);
        write(&root.join("downloads/partial.bin"), 300);
        write(&root.join("kv_cache/session1.bin"), 200);
        write(&root.join("logs/app.log"), 100);

        let usage = measure(&root);
        assert_eq!(usage.models_bytes, 4000);
        assert_eq!(usage.engines_bytes, 2000);
        assert_eq!(usage.database_bytes, 1000);
        assert_eq!(usage.vault_bytes, 500);
        assert_eq!(usage.downloads_bytes, 300);
        assert_eq!(usage.kv_cache_bytes, 200);
        // The log file is real disk usage and must be counted, but it belongs
        // to no named component.
        assert_eq!(usage.other_bytes, 100);
        assert_eq!(usage.total_bytes, 8100);
    }

    #[test]
    fn an_unlimited_limit_never_deletes_anything() {
        let root = temp_dir("unlimited");
        write(&root.join("kv_cache/a.bin"), 10_000);
        let db = MemoryDatabase::new_in_memory().unwrap();

        let outcome = enforce_limit(
            &ctx(&root, &db),
            EffectiveLimit { limit_mb: 0, source: LimitSource::UserSetting },
        );

        assert!(!outcome.ran);
        assert!(outcome.evicted.is_empty());
        assert!(root.join("kv_cache/a.bin").exists());
    }

    #[test]
    fn usage_within_budget_is_left_alone() {
        let root = temp_dir("within");
        write(&root.join("kv_cache/a.bin"), 1024);
        let db = MemoryDatabase::new_in_memory().unwrap();

        let outcome = enforce_limit(
            &ctx(&root, &db),
            EffectiveLimit { limit_mb: 1, source: LimitSource::Environment },
        );

        assert!(!outcome.ran);
        assert!(root.join("kv_cache/a.bin").exists());
    }

    /// The protected set is the whole point of tiering. Engine, database and
    /// vault must survive a budget far below their combined size, and the
    /// shortfall must be REPORTED rather than met by deleting them.
    #[test]
    fn the_engine_database_and_vault_are_never_evicted_and_the_shortfall_is_reported() {
        let root = temp_dir("protected");
        write(&root.join("engines/e1/llama-server.exe"), 3 * 1024 * 1024);
        write(&root.join("data/memory.db"), 1024 * 1024);
        write(&root.join("files/contract.pdf"), 1024 * 1024);
        write(&root.join("kv_cache/old.bin"), 1024 * 1024);
        let db = MemoryDatabase::new_in_memory().unwrap();

        let outcome = enforce_limit(
            &ctx(&root, &db),
            EffectiveLimit { limit_mb: 1, source: LimitSource::UserSetting },
        );

        assert!(outcome.ran);
        // Tier 1 was consumed...
        assert!(!root.join("kv_cache/old.bin").exists());
        // ...and everything protected survived.
        assert!(root.join("engines/e1/llama-server.exe").exists());
        assert!(root.join("data/memory.db").exists());
        assert!(
            root.join("files/contract.pdf").exists(),
            "user documents must never be deleted to satisfy a disk budget"
        );
        assert!(outcome.shortfall_bytes > 0, "the unmet remainder must be reported");
        assert!(outcome.reason.contains("still over"));
    }

    #[test]
    fn kv_blobs_go_before_downloads_and_oldest_goes_first() {
        let root = temp_dir("order");
        // 3 MB of KV blobs, 3 MB of downloads, budget 5 MB -> free ~1 MB.
        write(&root.join("kv_cache/old.bin"), 1024 * 1024);
        write(&root.join("kv_cache/new.bin"), 2 * 1024 * 1024);
        write(&root.join("downloads/partial.bin"), 3 * 1024 * 1024);

        // Make "old.bin" genuinely older than "new.bin". Uses std's
        // File::set_modified rather than a new dependency, and an explicit
        // backdate rather than a sleep - the ordering under test must be a
        // fact about mtimes, not about how fast the test machine creates files.
        let older = std::time::SystemTime::now() - std::time::Duration::from_secs(86_400);
        std::fs::OpenOptions::new()
            .write(true)
            .open(root.join("kv_cache/old.bin"))
            .unwrap()
            .set_modified(older)
            .unwrap();

        let db = MemoryDatabase::new_in_memory().unwrap();
        let outcome = enforce_limit(
            &ctx(&root, &db),
            EffectiveLimit { limit_mb: 5, source: LimitSource::UserSetting },
        );

        assert!(outcome.ran);
        assert!(!root.join("kv_cache/old.bin").exists(), "oldest KV blob goes first");
        assert!(
            root.join("downloads/partial.bin").exists(),
            "tier 2 must not be touched while tier 1 still satisfied the deficit"
        );
        assert_eq!(outcome.evicted.len(), 1);
        assert_eq!(outcome.evicted[0].kind, "kv_cache");
    }

    #[test]
    fn the_active_model_is_never_evicted_and_never_used_models_go_first() {
        let root = temp_dir("models");
        write(&root.join("models/active/model.gguf"), 2 * 1024 * 1024);
        write(&root.join("models/used/model.gguf"), 2 * 1024 * 1024);
        write(&root.join("models/never/model.gguf"), 2 * 1024 * 1024);

        let db = MemoryDatabase::new_in_memory().unwrap();
        db.settings.record_model_used("used").unwrap();

        let context = EvictionContext {
            app_data_dir: root.clone(),
            active_model_id: Some("active".to_string()),
            installed_models: vec![
                ("active".to_string(), root.join("models/active")),
                ("used".to_string(), root.join("models/used")),
                ("never".to_string(), root.join("models/never")),
            ],
            database: &db,
        };

        // 6 MB present, 5 MB budget -> one model must go.
        let outcome = enforce_limit(
            &context,
            EffectiveLimit { limit_mb: 5, source: LimitSource::UserSetting },
        );

        assert!(outcome.ran);
        assert!(
            root.join("models/active/model.gguf").exists(),
            "the loaded model must never be deleted out from under llama-server"
        );
        assert!(
            !root.join("models/never/model.gguf").exists(),
            "a downloaded-but-never-activated model is the weakest claim on disk"
        );
        assert!(
            root.join("models/used/model.gguf").exists(),
            "an activated model must outrank one that was never used"
        );
        assert!(db.settings.model_last_used("never").is_none());
    }

    #[test]
    fn a_missing_app_data_directory_measures_as_zero_rather_than_failing() {
        let root = temp_dir("missing").join("does_not_exist");
        let usage = measure(&root);
        assert_eq!(usage.total_bytes, 0);
        assert_eq!(usage.other_bytes, 0);
    }
}
